raccoongang/frontend-app-course-authoring

- src/CourseAuthoringPage.jsx
- src/advanced-settings/scss/AdvencedSettings.scss
- src/advanced-settings/setting-card/SettingCard.jsx
- src/advanced-settings/setting-card/__snapshots__/SettingCard.test.jsx.snap
- src/advanced-settings/setting-card/messages.js
- src/generic/Loading.jsx
- src/i18n/messages/ar.json
- src/i18n/messages/de.json
- src/i18n/messages/de_DE.json
- src/i18n/messages/es_419.json
- src/i18n/messages/fr.json
- src/i18n/messages/fr_CA.json
- src/i18n/messages/hi.json
- src/i18n/messages/it.json
- src/i18n/messages/it_IT.json
- src/i18n/messages/pt.json
- src/i18n/messages/pt_PT.json
- src/i18n/messages/ru.json
- src/i18n/messages/uk.json
- src/i18n/messages/zh_CN.json
**YouTrack**
- https://youtrack.raccoongang.com/issue/2U-174
- https://youtrack.raccoongang.com/issue/2U-173
> fix: fixed loader and changing help text on the page Advanced settings

- src/advanced-settings/AdvancedSettings.jsx
- src/advanced-settings/scss/AdvancedSettings.scss
- src/assets/scss/_variables.scss
- src/generic/help-sidebar/HelpSidebar.scss
- src/generic/styles.scss
- src/generic/sub-header/SubHeader.jsx
- src/generic/sub-header/SubHeader.scss
- src/schedule-and-details/ScheduleAndDetails.test.jsx
- src/schedule-and-details/basic-section/BasicSection.test.jsx
- src/schedule-and-details/basic-section/index.jsx
- src/schedule-and-details/basic-section/messages.js
- src/schedule-and-details/index.jsx
- src/schedule-and-details/learning-outcomes-section/messages.js
- src/schedule-and-details/messages.js
- src/schedule-and-details/schedule-section/messages.js
[YouTrack ticket](https://youtrack.raccoongang.com/issue/2U-219)
- Added SubHeader component
- Some refactoring
> feat: added SubHeader component

- src/advanced-settings/AdvancedSettings.jsx
- src/advanced-settings/data/thunks.js
- src/generic/internet-connection-alert/index.jsx
- src/schedule-and-details/hooks.jsx
- src/schedule-and-details/index.jsx
- src/schedule-and-details/license-section/constants.js
- src/schedule-and-details/license-section/hooks.jsx
- src/schedule-and-details/license-section/license-selector/index.jsx
- src/schedule-and-details/license-section/utils.js
[2U-204](https://youtrack.raccoongang.com/issue/2U-204)
[2U-210](https://youtrack.raccoongang.com/issue/2U-210)
> fix: internet connection on advanced settings and schedule&details pages

- src/advanced-settings/AdvancedSettings.test.jsx
- src/advanced-settings/modal-error/ModalErrorListItem.jsx
- src/advanced-settings/modal-error/messages.js
- src/advanced-settings/setting-card/SettingCard.jsx
- src/generic/help-sidebar/index.jsx
- src/generic/help-sidebar/messages.js
- src/i18n/messages/ar.json
- src/i18n/messages/de.json
- src/i18n/messages/de_DE.json
- src/i18n/messages/es_419.json
- src/i18n/messages/fr.json
- src/i18n/messages/fr_CA.json
- src/i18n/messages/hi.json
- src/i18n/messages/it.json
- src/i18n/messages/it_IT.json
- src/i18n/messages/pt.json
- src/i18n/messages/pt_PT.json
- src/i18n/messages/ru.json
- src/i18n/messages/uk.json
- src/i18n/messages/zh_CN.json
[YouTrack](https://youtrack.raccoongang.com/issue/2U-225)
**Tasks**
- add Proctoring exam url
- Some refactoring
> refactor: added Proctored exam link and refactoring

- src/CourseAuthoringRoutes.test.jsx
- src/generic/Wysiwyg.jsx
- src/generic/WysiwygEditor.jsx
- src/schedule-and-details/ScheduleAndDetails.test.jsx
- src/schedule-and-details/introducing-section/IntroducingSection.test.jsx
- src/schedule-and-details/introducing-section/index.jsx
[2U-237](https://youtrack.raccoongang.com/issue/2U-237)
[related PR](https://github.com/raccoongang/frontend-lib-content-components/pull/1)
> feat: Add wysiwyg editor

- src/schedule-and-details/requirements-section/index.jsx
[2U-270](https://youtrack.raccoongang.com/issue/2U-270)
> fix: [2U-270] requirements section with disabled flags

- src/advanced-settings/AdvancedSettings.jsx
- src/advanced-settings/AdvancedSettings.test.jsx
- src/generic/help-sidebar/HelpSidebar.test.jsx
- added tests for the HelpSidebar component
- added test for the Advanced settings page
> refactor: added tests for the HelpSidebar component

- src/grading-settings/grading-scale/GradingScale.jsx
- src/grading-settings/grading-scale/utils.js
- src/grading-settings/hooks.js
- fixed scale bar becomes empty after a few reloads
[YouTrack](https://youtrack.raccoongang.com/issue/2U-268)
> fix: fixed scale bar becomes empty after a few reloads

- src/constants.js
- src/course-updates/CourseUpdates.jsx
- src/course-updates/course-update/CourseUpdate.jsx
- src/course-updates/course-update/CourseUpdate.scss
- src/course-updates/course-update/messages.js
- src/course-updates/course-update/utils.js
- Fixed delete handler
- Add validations and validations check
[2u-302](https://youtrack.raccoongang.com/issue/2U-302)
[2u-303](https://youtrack.raccoongang.com/issue/2U-303)
> Fix: Course update validations and delete

- src/grading-settings/GradingSettings.jsx
- src/grading-settings/assignment-section/AssignmentSection.scss
- src/grading-settings/scss/_variables.scss
> refactor: design fixes

- src/course-team/CourseTeam.jsx
- src/course-team/CourseTeam.test.jsx
- src/course-team/__mocks__/courseTeam.js
- src/course-team/__mocks__/courseTeamWithOneUser.js
- src/course-team/data/api.js
- src/course-team/data/selectors.js
- src/course-team/data/slice.js
- src/course-team/data/thunk.js
- src/course-team/hooks.jsx
- src/course-team/info-modal/InfoModal.jsx
- src/course-team/info-modal/InfoModal.test.jsx
- src/course-team/info-modal/messages.js
- src/course-team/utils.js
- src/i18n/messages/ar.json
- src/i18n/messages/de.json
- src/i18n/messages/de_DE.json
- src/i18n/messages/es_419.json
- src/i18n/messages/fr.json
- src/i18n/messages/fr_CA.json
- src/i18n/messages/hi.json
- src/i18n/messages/it.json
- src/i18n/messages/it_IT.json
- src/i18n/messages/pt.json
- src/i18n/messages/pt_PT.json
- src/i18n/messages/ru.json
- src/i18n/messages/uk.json
- src/i18n/messages/zh_CN.json
- Refactor error messages
- Refactor camelCase data
[2u-392](https://youtrack.raccoongang.com/issue/2U-392)
> Fix: Course team error messages

- src/studio-home/tabs-section/archived-tab/index.jsx
- src/studio-home/tabs-section/courses-tab/index.jsx
- src/studio-home/tabs-section/libraries-tab/index.jsx
- src/studio-home/tabs-section/utils.js
- src/studio-home/tabs-section/utils.test.js
- added alphabetically sorting for course list
[YouTrack](https://youtrack.raccoongang.com/issue/2U-530)
> feat: [2U-530] added alphabetically sorting for course list

- src/course-updates/course-update/CourseUpdate.jsx
- src/course-updates/update-form/UpdateForm.jsx
- src/course-updates/update-form/utils.js
- Add checking date in form
[2u-631](https://youtrack.raccoongang.com/issue/2U-631)
> fix: Course updates - wrong datepicker value

- src/export-page/data/constants.js
- src/export-page/export-sidebar/ExportSidebar.jsx
- src/export-page/utils.js
https://youtrack.raccoongang.com/issue/2U-606
https://youtrack.raccoongang.com/issue/2U-630
> fix: [2U-606] fix date format and help link on export

- src/advanced-settings/AdvancedSettings.jsx
- src/advanced-settings/scss/AdvancedSettings.scss
- src/course-team/CourseTeam.jsx
- src/course-team/CourseTeam.scss
- src/generic/help-sidebar/HelpSidebar.scss
- src/grading-settings/GradingSettings.jsx
- src/grading-settings/scss/GradingSettings.scss
- src/schedule-and-details/ScheduleAndDetails.scss
- src/schedule-and-details/index.jsx
- fixed sidebar margin-top
[YouTrack](https://youtrack.raccoongang.com/issue/2U-692)
> fix: [2U-692] fixed sidebar margin top

- src/course-outline/CourseOutline.jsx
- src/course-outline/data/thunk.js
- Add saving processing for highlights
- Add saving processing for enable highlights
[2u-696](https://youtrack.raccoongang.com/issue/2U-696)
> fix: Course outline - Saving processing for highlights

- src/constants.js
- src/grading-settings/deadline-section/DeadlineSection.test.jsx
- src/grading-settings/deadline-section/index.jsx
- fixed deadline section
[YouTrack](https://youtrack.raccoongang.com/issue/2U-703)
> fix: [2U-703] fixed deadline section

- package-lock.json
- package.json
- src/grading-settings/grading-scale/GradingScale.jsx
- src/grading-settings/grading-scale/react-ranger.js
- transferred [React-ranger lib](https://github.com/TanStack/ranger)
- **TODO:** In the future, we will wait for the original library to be updated (or refactor the ported code).
[YouTrack](https://youtrack.raccoongang.com/issue/2U-633)
> refactor: transferred React-ranger lib

- src/studio-home/__mocks__/studioHomeMock.js
- src/studio-home/card-item/CardItem.test.jsx
- src/studio-home/card-item/index.jsx
[2U-707](https://youtrack.raccoongang.com/issue/2U-707)
> feat: made the courses as read-only if old mongo store

- src/studio-home/tabs-section/index.jsx
[2U-539](https://youtrack.raccoongang.com/issue/2U-539)
> fix: redirect to library MFE

- src/course-outline/CourseOutline.jsx
- src/course-outline/CourseOutline.test.jsx
- src/course-outline/__mocks__/index.js
- src/course-outline/hooks.jsx
- src/course-outline/messages.js
- src/export-page/CourseExportPage.jsx
- src/export-page/CourseExportPage.test.jsx
- src/export-page/messages.js
- src/i18n/messages/ar.json
- src/i18n/messages/de.json
- src/i18n/messages/de_DE.json
- src/i18n/messages/es_419.json
- src/i18n/messages/fr.json
- src/i18n/messages/fr_CA.json
- src/i18n/messages/hi.json
- src/i18n/messages/it.json
- src/i18n/messages/it_IT.json
- src/i18n/messages/pt.json
- src/i18n/messages/pt_PT.json
- src/i18n/messages/ru.json
- src/i18n/messages/uk.json
- src/i18n/messages/zh_CN.json
- src/import-page/CourseImportPage.jsx
- src/import-page/CourseImportPage.test.jsx
- src/import-page/messages.js
- src/studio-home/StudioHome.jsx
- src/studio-home/StudioHome.test.jsx
- src/studio-home/messages.js
Added the page title for new MFE studio pages:
- Course-outline
- Export/import pages
- Studio home
[YouTrack](https://youtrack.raccoongang.com/issue/2U-704)
> fix: [2U-704] provided the page title for new MFE studio pages

- src/course-outline/CourseOutline.jsx
- src/course-outline/enable-highlights-modal/EnableHighlightsModal.jsx
- src/course-outline/enable-highlights-modal/EnableHighlightsModal.test.jsx
- src/course-outline/highlights-modal/HighlightsModal.jsx
- src/course-outline/status-bar/StatusBar.jsx
- Fixed links in modals and status bar
[2u-693](https://youtrack.raccoongang.com/issue/2U-693)
[2u-694](https://youtrack.raccoongang.com/issue/2U-694)
[2u-695](https://youtrack.raccoongang.com/issue/2U-695)
> fix: Course outline - Highlights links

- src/constants.js
- src/course-unit/CourseUnit.jsx
- src/course-unit/add-component/AddComponent.jsx
- src/course-unit/add-component/AddComponent.test.jsx
- src/course-unit/add-component/ComponentIcon.jsx
- src/course-unit/constants.js
- src/course-unit/data/api.js
- src/course-unit/data/slice.js
- src/course-unit/data/thunk.js
- src/course-unit/hooks.jsx
**Description:** make discussion and drag-and-drop button functional
**Youtrack:** https://youtrack.raccoongang.com/issue/AXIMST-16
> feat: [AXIMST-16] Course unit - make discussion and drag-and-drop button functional

- src/course-outline/CourseOutline.test.jsx
- src/course-outline/hooks.jsx
**Description:** fix tests after upstream sync
**Youtrack:** https://youtrack.raccoongang.com/issue/AXIMST-38
> fix: [AXIMST-38] Unit page - fix tests after upstream sync

- src/course-unit/CourseUnit.test.jsx
- src/course-unit/__mocks__/courseCreateXblock.js
- src/course-unit/__mocks__/index.js
- src/course-unit/add-component/AddComponent.jsx
- src/course-unit/add-component/AddComponent.test.jsx
- src/course-unit/data/thunk.js
- src/course-unit/hooks.jsx
- src/utils.js
**Description:** make Problem button functional
**Youtrack:** https://youtrack.raccoongang.com/issue/AXIMST-17
> feat: [AXIMST-17] Course unit - make Problem button functional

- src/course-unit/CourseUnit.jsx
- src/course-unit/breadcrumbs/Breadcrumbs.jsx
- src/course-unit/breadcrumbs/Breadcrumbs.test.jsx
- src/utils.js
**Description:** 
- refactoring unit breadcrumbs
- create correct internal path
**Youtrack:** https://youtrack.raccoongang.com/issue/AXIMST-367
> fix: [AXIMST-367] Course unit - refactoring unit breadcrumbs and create correct internal path

- src/course-unit/add-component/AddComponent.jsx
**Description:** fix internal path to problem editor page
**Youtrack:** https://youtrack.raccoongang.com/issue/AXIMST-369
> fix: [AXIMST-369] fix internal path to problem editor page

- package-lock.json
- package.json
- src/CourseAuthoringRoutes.jsx
- src/constants.js
- src/course-unit/CourseUnit.jsx
- src/course-unit/CourseUnit.test.jsx
- src/course-unit/__mocks__/courseSectionVertical.js
- src/course-unit/__mocks__/courseUnit.js
- src/course-unit/__mocks__/index.js
- src/course-unit/course-sequence/Sequence.jsx
- src/course-unit/course-sequence/hooks.js
- src/course-unit/course-sequence/sequence-navigation/SequenceNavigation.jsx
- src/course-unit/course-sequence/sequence-navigation/SequenceNavigationDropdown.jsx
- src/course-unit/course-sequence/sequence-navigation/SequenceNavigationTabs.jsx
- src/course-unit/course-sequence/sequence-navigation/UnitButton.jsx
- src/course-unit/data/api.js
- src/course-unit/data/selectors.js
- src/course-unit/data/slice.js
- src/course-unit/data/thunk.js
- src/course-unit/data/utils.js
- src/course-unit/header-title/HeaderTitle.jsx
- src/course-unit/header-title/HeaderTitle.test.jsx
- src/course-unit/hooks.jsx
[YouTrack](https://youtrack.raccoongang.com/issue/AXIMST-14)
> feat: [AXIMST-14] Course unit - New unit btn, Replacing LMS endpoints with CMS endpoints, alert internet connection

- src/course-unit/CourseUnit.test.jsx
- src/course-unit/add-component/AddComponent.jsx
- src/course-unit/add-component/AddComponent.test.jsx
**Description:** make video button functional
**Youtrack:** https://youtrack.raccoongang.com/issue/AXIMST-18
> feat: [AXIMST-18] Unit page - make video button functional

- src/course-unit/course-sequence/sequence-navigation/SequenceNavigationTabs.jsx
**Description:** fix correct internal route on create new unit
**Youtrack:** https://youtrack.raccoongang.com/issue/AXIMST-371
> fix: [AXIMST-371] Unit page - fix correct internal route on create new unit

- src/course-unit/CourseUnit.test.jsx
- src/course-unit/__mocks__/courseUnit.js
- src/course-unit/data/thunk.js
- src/course-unit/hooks.jsx
**YouTrack**
https://youtrack.raccoongang.com/issue/AXIMST-399
> fix: [AXIMST-399] Course unit - Update of sequence block title after changing unit name

- src/course-unit/course-sequence/hooks.js
**YouTrack**
https://youtrack.raccoongang.com/issue/AXIMST-416
> fix: [AXIMST-416] Course-unit - Fixed prev and next buttons

- src/course-unit/CourseUnit.jsx
- src/course-unit/CourseUnit.scss
- src/course-unit/CourseUnit.test.jsx
- src/course-unit/hooks.jsx
- src/course-unit/messages.js
- src/i18n/messages/ar.json
- src/i18n/messages/de.json
- src/i18n/messages/de_DE.json
- src/i18n/messages/es_419.json
- src/i18n/messages/fa_IR.json
- src/i18n/messages/fr.json
- src/i18n/messages/fr_CA.json
- src/i18n/messages/hi.json
- src/i18n/messages/it.json
- src/i18n/messages/it_IT.json
- src/i18n/messages/pt.json
- src/i18n/messages/pt_PT.json
- src/i18n/messages/ru.json
- src/i18n/messages/uk.json
- src/i18n/messages/zh_CN.json
**YouTrack**
https://youtrack.raccoongang.com/issue/AXIMST-25
> feat: [AXIMST-25] Course unit - Alert notification about unpublished changes

- src/course-unit/CourseUnit.jsx
- src/course-unit/CourseUnit.test.jsx
- src/course-unit/hooks.jsx
**YouTrack**
https://youtrack.raccoongang.com/issue/AXIMST-427
> fix: [AXIMST-427] Course unit - Fixed unpublished changes alert

- src/textbooks/textbook-card/TextbookCard.scss
- Fixed chapters texts overlap
[AXIMST-434](https://youtrack.raccoongang.com/issue/AXIMST-434)
[AXIMST-435](https://youtrack.raccoongang.com/issue/AXIMST-435)
> fix: [AXIMST-434-435] Textbooks: fixed textbook chapter texts

- package-lock.json
- src/course-unit/course-xblock/urls.js
**Description:** Unit page - change iframe pararm for display xblock content
**Youtrack:** https://youtrack.raccoongang.com/issue/AXIMST-27
> fix: [AXIMST-27] Unit page - change iframe pararm for display xblock content

- src/course-unit/CourseUnit.test.jsx
- src/course-unit/data/thunk.js
**YouTrack**
https://youtrack.raccoongang.com/issue/AXIMST-470
> fix: [AXIMST-470] Course unit - Fixed sidebar status after deleting or duplicating xblock

- src/course-unit/sidebar/Sidebar.scss
- src/course-unit/sidebar/components/sidebar-footer/UnitVisibilityInfo.jsx
- src/course-unit/sidebar/messages.js
- src/i18n/messages/ar.json
- src/i18n/messages/de.json
- src/i18n/messages/de_DE.json
- src/i18n/messages/es_419.json
- src/i18n/messages/fa_IR.json
- src/i18n/messages/fr.json
- src/i18n/messages/fr_CA.json
- src/i18n/messages/hi.json
- src/i18n/messages/it.json
- src/i18n/messages/it_IT.json
- src/i18n/messages/pt.json
- src/i18n/messages/pt_PT.json
- src/i18n/messages/ru.json
- src/i18n/messages/uk.json
- src/i18n/messages/zh_CN.json
**YouTrack**
https://youtrack.raccoongang.com/issue/AXIMST-472
> fix: [AXIMST-472] Course unit - Fixed sidebar visibility notification

- src/course-unit/CourseUnit.test.jsx
- src/course-unit/data/thunk.js
**YouTrack**
https://youtrack.raccoongang.com/issue/AXIMST-473
> fix: [AXIMST-473] Course unit - Fixed sidebar publish status

- src/course-unit/CourseUnit.test.jsx
- src/course-unit/data/api.js
**YouTrack**
https://youtrack.raccoongang.com/issue/AXIMST-471
> fix: [AXIMST-471] Course unit - Fixed configure course unit request

- src/course-unit/data/thunk.js
**YouTrack**
https://youtrack.raccoongang.com/issue/AXIMST-480
> fix: [AXIMST-480] Course unit - Fixed paste notification behavior after switching a unit

- src/course-unit/clipboard/paste-component/index.jsx
**YouTrack**
https://youtrack.raccoongang.com/issue/AXIMST-478
> fix: [AXIMST-478] Course unit - Fixed copy-paste tooltip

- src/course-unit/CourseUnit.jsx
- src/course-unit/course-xblock/CourseXBlock.jsx
- src/course-unit/course-xblock/CourseXBlock.test.jsx
**Description:** Unit page - make xblock edit functional
**Youtrack:** https://youtrack.raccoongang.com/issue/AXIMST-29
> feat: [AXIMST-29] Unit page - make xblock edit functional

- src/certificates/certificate-details/CertificateDetailsForm.jsx
- src/certificates/certificate-section/CertificateSection.jsx
- src/certificates/certificate-signatories/CertificateSignatories.jsx
- src/certificates/certificate-signatories/signatory/Signatory.jsx
- src/certificates/certificate-signatories/signatory/SignatoryForm.jsx
- src/certificates/scss/Certificates.scss
- src/generic/modal-dropzone/ModalDropzone.jsx
- src/generic/modal-dropzone/messages.js
- src/i18n/messages/ar.json
- src/i18n/messages/de.json
- src/i18n/messages/de_DE.json
- src/i18n/messages/es_419.json
- src/i18n/messages/fa_IR.json
- src/i18n/messages/fr.json
- src/i18n/messages/fr_CA.json
- src/i18n/messages/hi.json
- src/i18n/messages/it.json
- src/i18n/messages/it_IT.json
- src/i18n/messages/pt.json
- src/i18n/messages/pt_PT.json
- src/i18n/messages/ru.json
- src/i18n/messages/uk.json
- src/i18n/messages/zh_CN.json
[AXIMST-503](https://youtrack.raccoongang.com/issue/AXIMST-503) Page UI issues
> fix: [AXIMST-503] certificates view UI

- src/certificates/certificate-details/CertificateDetailsForm.jsx
- src/certificates/certificate-section/CertificateSection.jsx
- src/certificates/certificate-signatories/CertificateSignatories.jsx
- src/certificates/certificate-signatories/signatory/SignatoryForm.jsx
- src/generic/modal-dropzone/ModalDropzone.jsx
- src/generic/modal-dropzone/messages.js
- src/i18n/messages/ar.json
- src/i18n/messages/de.json
- src/i18n/messages/de_DE.json
- src/i18n/messages/es_419.json
- src/i18n/messages/fa_IR.json
- src/i18n/messages/fr.json
- src/i18n/messages/fr_CA.json
- src/i18n/messages/hi.json
- src/i18n/messages/it.json
- src/i18n/messages/it_IT.json
- src/i18n/messages/pt.json
- src/i18n/messages/pt_PT.json
- src/i18n/messages/ru.json
- src/i18n/messages/uk.json
- src/i18n/messages/zh_CN.json
[AXIMST-482](https://youtrack.raccoongang.com/issue/AXIMST-482) Page UI issues
> fix: [AXIMST-482] certificates create UI

- src/certificates/data/thunks.js
- src/group-configurations/data/slice.js
- src/group-configurations/data/thunk.js
- src/group-configurations/hooks.jsx
[AXIMST-509](https://youtrack.raccoongang.com/issue/AXIMST-509) [certificates_edit] The page reloads after the user saves changes to the certificate or signature
> fix: [AXIMST-509] The page reloads after the user saves changes to the certificate or signature

- src/course-unit/CourseUnit.scss
- src/course-unit/course-xblock/CourseXblock.scss
- src/course-unit/header-title/HeaderTitle.jsx
- src/course-unit/header-title/HeaderTitle.scss
**YouTrack**
https://youtrack.raccoongang.com/issue/AXIMST-512/dragdrop-the-DD-button-goes-up-if-the-xblock-has-access-restriction-notification
> fix: [AXIMST-512] Course unit - Fixed drag and drop buttons

- src/course-unit/sidebar/Sidebar.scss
- src/course-unit/sidebar/components/sidebar-footer/ActionButtons.jsx
- src/generic/divider/Divider.jsx
- src/generic/divider/Divider.scss
- src/generic/divider/index.jsx
- src/generic/styles.scss
[YouTrack](https://youtrack.raccoongang.com/issue/AXIMST-525/Separate-the-copy-unit-button)
> feat: [AXIMST-525] Course unit - Separated the copy unit button

- src/course-unit/CourseUnit.test.jsx
- src/course-unit/course-sequence/CourseSequence.scss
- src/course-unit/course-sequence/sequence-navigation/SequenceNavigationTabs.jsx
[YouTrack](https://youtrack.raccoongang.com/issue/AXIMST-507/Demo-review-additional-requests)
> refactor: [AXIMST-507] Course unit - Changed Paste unit UI

- src/course-unit/CourseUnit.test.jsx
- src/course-unit/clipboard/paste-notification/index.jsx
- src/course-unit/data/selectors.js
- src/course-unit/hooks.jsx
[YouTrack](https://youtrack.raccoongang.com/issue/AXIMST-558/unit-an-error-appears-if-a-user-opens-the-unit-page)
> fix: [AXIMST-558] Course unit - Fixed loading errors and PropTypes

- src/textbooks/textbook-form/TextbookForm.scss
[AXIMST-605](https://youtrack.raccoongang.com/issue/AXIMST-605/request-within-demo-Add-link-to-preview-upload-modal)
> feat: [AXIMST-605] add file name to upload preview modal

- src/course-unit/CourseUnit.jsx
- src/course-unit/CourseUnit.scss
- src/course-unit/clipboard/paste-notification/index.jsx
- src/course-unit/course-xblock/CourseXBlock.jsx
- src/course-unit/course-xblock/CourseXblock.scss
[YouTrack](https://youtrack.raccoongang.com/issue/AXIMST-656/unitxblock-Space-between-xblocks-must-be-reduced)
> fix: [AXIMST-656] Course unit - Fixed space between xblocks

- src/group-configurations/common/UsageList.jsx
- src/group-configurations/experiment-configurations-section/ExperimentCard.jsx
- src/group-configurations/experiment-configurations-section/ExperimentForm.jsx
- src/group-configurations/experiment-configurations-section/constants.js
- src/group-configurations/experiment-configurations-section/index.jsx
- src/group-configurations/experiment-configurations-section/messages.js
- src/group-configurations/experiment-configurations-section/utils.js
- src/group-configurations/experiment-configurations-section/utils.test.js
- src/hooks.js
[experimentgroup-Description-field-should-be-textarea](https://youtrack.raccoongang.com/issue/AXIMST-597/experimentgroup-Description-field-should-be-textarea)
[tooltip-incorrect-delete-icon-tooltip-text-for-experiment-group-configuration](https://youtrack.raccoongang.com/issue/AXIMST-670/tooltip-incorrect-delete-icon-tooltip-text-for-experiment-group-configuration)
[warning-Group-configuration-warning-messages-arent-fully-covered](https://youtrack.raccoongang.com/issue/AXIMST-673/warning-Group-configuration-warning-messages-arent-fully-covered)
[groupconfigurationsview-Direct-link-to-group-config-doesnt-lead-to-the-group-anchor-point-on-the-page](https://youtrack.raccoongang.com/issue/AXIMST-672/groupconfigurationsview-Direct-link-to-group-config-doesnt-lead-to-the-group-anchor-point-on-th …
> fix: [AXIMST-597, 670, 673, 672, 671, 596] Group configurations - Bugs

- src/course-unit/CourseUnit.jsx
- src/course-unit/CourseUnit.scss
- src/course-unit/course-xblock/CourseXBlock.jsx
Technical fix after new changes in the upstream repository.
> fix: fixing problems with dnd after sync

- src/course-unit/course-xblock/CourseXBlock.jsx
- src/course-unit/course-xblock/CourseXBlock.test.jsx
- src/course-unit/course-xblock/messages.js
[AXIMST-560](https://youtrack.raccoongang.com/issue/AXIMST-560) [Unit page] Display tag count for each component
> feat: [AXIMST-560] display tags count on each component

- src/group-configurations/common/UsageList.jsx
[warning-icon-isnt-aligned-with-text](https://youtrack.raccoongang.com/issue/AXIMST-714/warning-icon-isnt-aligned-with-text)
> fix: [AXIMST-714] icon is aligned with text

- src/course-unit/course-xblock/xblock-content/iframe-wrapper/iframe-wrapper.js
[YouTrack](https://youtrack.raccoongang.com/agiles/104-1224/105-3378?issue=AXIMST-718)
> fix: [AXIMST-718] fixed problem with CSRF token

- src/course-unit/course-xblock/xblock-content/XBlockContent.jsx
- src/course-unit/course-xblock/xblock-content/iframe-wrapper/iframe-wrapper.js
- src/course-unit/data/api.js
- src/course-unit/data/selectors.js
- src/course-unit/data/slice.js
- src/course-unit/data/thunk.js
- src/course-unit/hooks.jsx
[YouTrack](https://youtrack.raccoongang.com/issue/AXIMST-718/ORA-An-error-appear-while-rendering-the-ORA-xblock)
> fix: [AXIMST-718] Course unit - Created logic for getting CSRF token

- src/course-unit/course-xblock/CourseXBlock.jsx
- src/course-unit/course-xblock/CourseXBlock.test.jsx
- src/course-unit/course-xblock/messages.js
- src/course-unit/course-xblock/xblock-content/XBlockContent.jsx
- src/course-unit/hooks.jsx
[AXIMST-746](https://youtrack.raccoongang.com/issue/AXIMST-746) (NEW) PERFORMANCE ISSUE (UNIT)
> refactor: [AXIMST-746] Unit page performance refactoring

- src/course-unit/course-xblock/xblock-content/iframe-wrapper/iframe-wrapper.js
- src/course-unit/data/thunk.js
[YouTrack](https://youtrack.raccoongang.com/issue/AXIMST-767/paste-new-files-added-notification-doesnt-appear-after-pasting-the-component)
> fix: [AXIMST-767] fixed new files alert

- src/course-unit/CourseUnit.jsx
- src/course-unit/CourseUnit.test.jsx
- src/course-unit/data/selectors.js
- src/course-unit/data/slice.js
- src/course-unit/data/thunk.js
- src/course-unit/hooks.jsx
[YouTrack](https://youtrack.raccoongang.com/issue/AXIMST-769/limitedstaff-an-error-appears-if-a-limited-staff-opens-the-unit-page-via-a-direct-link)
> fix: [AXIMST-769] Course unit - Added display of error alert
